### ISSUE TITLE
Restringir máximo de matrículas obrigatórias e/ou optativas

### ISSUE THREAD

**Issue by Lucas-Angelo** [Lucas-Angelo/ProjetoDeSoftware-Lab01#12]

**Comment by Lucas-Angelo** [comment]
![image](https://user-images.githubusercontent.com/49598959/130621958-8621a3ad-54ed-4635-9c4a-2135c70a7924.png)
Variáveis não utilizadas/verificadas ao matrícular, tem que dar utilidade pra elas... @guizombas

**Comment by Lucas-Angelo** [comment]
Além disso, esses comentários ai do cntrl+c e cntrl+v tão feios...

**Comment by guizombas** [comment]
Isso vai ter que ser feito quando for feito a matrícula do aluno, na main mesmo, porque tem que ter o acesso das turmas pra ver se o aluno já extrapolou o limite.

**Comment by Lucas-Angelo** [comment]
@Henrikkee quando for fazer sua parte, lembra de tratar isto
